language: python
python:
  - "2.7"
  - "3.5"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda

    # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION sphinx
    - pip install --user travis-sphinx
    - python setup.py install

script:
    - travis-sphinx build

after_success:
    - travis-sphinx deploy
